# Generated by Django 3.1.1 on 2020-09-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(default=0),
        ),
    ]
